language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install -n

script:
  - phpunit -c app
