language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer install -n

script:
  - app/console doctrine:database:create
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load --no-interaction
  - bin/phpunit -c app
