etheriq_admin_blog:
    resource: "@EtheriqAdminBlogBundle/Resources/config/routing.yml"

etheriq_blog:
    resource: "@EtheriqBlogBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine

