etheriq_admin_blog:
    resource: "@EtheriqAdminBlogBundle/Resources/config/routing.yml"
    prefix:   /

etheriq_blog:
    resource: "@EtheriqBlogBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

