/*!
 * jQCloud Plugin for jQuery
 *
 * Version 1.0.4
 *
 * Copyright 2011, Luca Ongaro
 * Licensed under the MIT license.
 *
 * Date: 2013-05-09 18:54:22 +0200
 */
(function(a){a.fn.jQCloud=function(c,d){var f=this;var e=f.attr("id")||Math.floor((Math.random()*1000000)).toString(36);var g={width:f.width(),height:f.height(),center:{x:((d&&d.width)?d.width:f.width())/2,y:((d&&d.height)?d.height:f.height())/2},delayedMode:c.length>50,shape:false,encodeURI:true,removeOverflowing:true};d=a.extend(g,d||{});f.addClass("jqcloud").width(d.width).height(d.height);if(f.css("position")==="static"){f.css("position","relative")}var b=function(){var j=function(s,q){var p=function(t,i){if(Math.abs(2*t.offsetLeft+t.offsetWidth-2*i.offsetLeft-i.offsetWidth)<t.offsetWidth+i.offsetWidth){if(Math.abs(2*t.offsetTop+t.offsetHeight-2*i.offsetTop-i.offsetHeight)<t.offsetHeight+i.offsetHeight){return true}}return false};var r=0;for(r=0;r<q.length;r++){if(p(s,q[r])){return true}}return false};for(var k=0;k<c.length;k++){c[k].weight=parseFloat(c[k].weight,10)}c.sort(function(p,i){if(p.weight<i.weight){return 1}else{if(p.weight>i.weight){return -1}else{return 0}}});var n=(d.shape==="rectangular")?18:2,h=[],l=d.width/d.height;var m=function(r,A){var D=e+"_word_"+r,s="#"+D,B=6.28*Math.random(),p=0,t=0,F=0,v=5,z="",C="",u;A.html=a.extend(A.html,{id:D});if(A.html&&A.html["class"]){z=A.html["class"];delete A.html["class"]}if(c[0].weight>c[c.length-1].weight){v=Math.round((A.weight-c[c.length-1].weight)/(c[0].weight-c[c.length-1].weight)*9)+1}u=a("<span>").attr(A.html).addClass("w"+v+" "+z);if(A.link){if(typeof A.link==="string"){A.link={href:A.link}}if(d.encodeURI){A.link=a.extend(A.link,{href:encodeURI(A.link.href).replace(/'/g,"%27")})}C=a("<a>").attr(A.link).text(A.text)}else{C=A.text}u.append(C);if(!!A.handlers){for(var i in A.handlers){if(A.handlers.hasOwnProperty(i)&&typeof A.handlers[i]==="function"){a(u).bind(i,A.handlers[i])}}}f.append(u);var y=u.width(),x=u.height(),q=d.center.x-y/2,w=d.center.y-x/2;var E=u[0].style;E.position="absolute";E.left=q+"px";E.top=w+"px";while(j(u[0],h)){if(d.shape==="rectangular"){t++;if(t*n>(1+Math.floor(F/2))*n*((F%4%2)===0?1:l)){t=0;F++}switch(F%4){case 1:q+=n*l+Math.random()*2;break;case 2:w-=n+Math.random()*2;break;case 3:q-=n*l+Math.random()*2;break;case 0:w+=n+Math.random()*2;break}}else{p+=n;B+=(r%2===0?1:-1)*n;q=d.center.x-(y/2)+(p*Math.cos(B))*l;w=d.center.y+p*Math.sin(B)-(x/2)}E.left=q+"px";E.top=w+"px"}if(d.removeOverflowing&&(q<0||w<0||(q+y)>d.width||(w+x)>d.height)){u.remove();return}h.push(u[0]);if(a.isFunction(A.afterWordRender)){A.afterWordRender.call(u)}};var o=function(i){i=i||0;if(!f.is(":visible")){setTimeout(function(){o(i)},10);return}if(i<c.length){m(i,c[i]);setTimeout(function(){o(i+1)},10)}else{if(a.isFunction(d.afterCloudRender)){d.afterCloudRender.call(f)}}};if(d.delayedMode){o()}else{a.each(c,m);if(a.isFunction(d.afterCloudRender)){d.afterCloudRender.call(f)}}};setTimeout(function(){b()},10);return f}})(jQuery);