homepage:
    pattern:  /{page}
    defaults: { _controller: EtheriqBlogBundle:Blog:showBlogMainPage, page: 1 }
    requirements:
            page:  \d+

blog_showInfo:
    pattern:  /blog/show/{slug}
    defaults: { _controller: EtheriqBlogBundle:Blog:showBlogInfo }

comment_edit:
    pattern:  /blog/comment/edit/{id}/{slug}
    defaults: { _controller: EtheriqBlogBundle:Blog:editComment }

comment_delete:
    pattern:  /blog/comment/delete/{id}/{slug}
    defaults: { _controller: EtheriqBlogBundle:Blog:deleteComment }

blog_edit:
    pattern:  /blog/edit/{slug}
    defaults: { _controller: EtheriqBlogBundle:Blog:editBlogInfo }
    requirements:
            _method: post|put

blog_delete:
    pattern:  /blog/delete/{slug}
    defaults: { _controller: EtheriqBlogBundle:Blog:deleteBlogInfo }
    requirements:
            _method: post|delete

blog_category:
    pattern:  /blog/category/{slug}/{page}
    defaults: { _controller: EtheriqBlogBundle:Blog:showBlogsByCategory, page: 1 }

blog_tag:
    pattern:  /blog/tag/{slug}/{page}
    defaults: { _controller: EtheriqBlogBundle:Blog:showBlogsByTag, page: 1 }

blog_find:
    pattern:  /blog/find
    defaults: { _controller: EtheriqBlogBundle:Blog:find }

blog_search:
    pattern:  /blog/search/{slug}/{page}
    defaults: { _controller: EtheriqBlogBundle:Blog:searchBlogsByTitle, page: 1, slug: '' }
    requirements:
            page:  \d+

blog_search_error:
    pattern:  /blog/search/
    defaults: { _controller: EtheriqBlogBundle:Blog:showBlogMainPage, page: 1  }

blog_new_article:
    pattern:  /blog/new
    defaults: { _controller: EtheriqBlogBundle:Blog:newBlogArticle }

guest:
    pattern:  /guest/{page}
    defaults: { _controller: EtheriqBlogBundle:Guest:showGuest, page: 1 }
    requirements:
            page:  \d+

guest_showInfo:
    pattern:  /guest/show/{slug}
    defaults: { _controller: EtheriqBlogBundle:Guest:showGuestInfo }

guest_deleteItem:
    pattern:  /guest/delete/{slug}
    defaults: { _controller: EtheriqBlogBundle:Guest:deleteGuestItem }
    requirements:
            _method: post|delete

about:
    pattern:  /about
    defaults: { _controller: EtheriqBlogBundle:AboutMe:showAboutMePage }

set_locale:
    pattern: /setLocale/{loc}
    defaults: { _controller: EtheriqBlogBundle:Additional:setLocale }