admin_blog_login:
    pattern:  /{_locale}/login
    defaults: { _controller: EtheriqAdminBlogBundle:BlogSecurity:login }
    requirements:
            _locale: en|ru|ua

admin_blog_registeer_user:
    pattern:  /{_locale}/register
    defaults: { _controller: EtheriqAdminBlogBundle:Registration:registerr }
    requirements:
            _locale: en|ru|ua

admin_blog_showProfile_user:
    pattern: /{_locale}/profile
    defaults: { _controller: EtheriqAdminBlogBundle:BlogSecurity:showProfileInfo }
    requirements:
            _locale: en|ru|ua

admin_blog_edit_profile:
    pattern: /{_locale}/profile/edit
    defaults: { _controller: EtheriqAdminBlogBundle:BlogSecurity:edit }
    requirements:
            _locale: en|ru|ua
#
#admin_blog_login_check:
#    pattern:  /{_locale}/login_check
#    defaults: { _controller: EtheriqAdminBlogBundle:BlogSecurity:loginCheck }
#    requirements:
#            _locale: en|ru|ua
##
#admin_blog_logout:
#    pattern:  /{_locale}/logout
#    defaults: { _controller: EtheriqAdminBlogBundle:BlogSecurity:logout }
#    requirements:
#                _locale: en|ru|ua

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}


#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
