parameters:
#    etheriq_admin_blog.example.class: Etheriq\AdminBlogBundle\Example

services:
#    etheriq_admin_blog.example:
#        class: %etheriq_admin_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
